
version: '2'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

  app:
    build:
      context: ../
      dockerfile: contrib/Dockerfile
    ports:
      - "8282:8282"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=postgres
      - DEBUG=True
    links:
      - db
